import Link from 'next/link';
import { ContactCTA, Services, Process, Portfolio, s } from '@/components/Site';
import { company, visibleProjects } from '@/data/site';
export default function Home() { return <>
  <section className={s.hero}><div className={s.container}><div className={s.heroContent}><p className={s.eyebrow}>FROM IDEA TO REALITY</p><h1>{company.heroTitle}</h1><p className={s.lead}>{company.heroDescription}</p><div className={s.buttons}><Link className={s.button} href={visibleProjects.length ? '/portfolio' : '/services'}>{visibleProjects.length ? '포트폴리오 보기' : '사업영역 보기'} <span aria-hidden="true">↗</span></Link><Link className={s.outlineButton} href="/contact">문의하기 <span aria-hidden="true">↗</span></Link></div><p className={s.heroFoot}>DESIGN <span>—</span> SOURCING <span>—</span> MANUFACTURING</p></div><div className={s.heroArt} aria-hidden="true"><div className={s.orbit}/><div className={s.orbitInner}/><div className={s.objectBack}/><div className={s.objectFront}><span>JNB</span><i/><i/><i/></div><span className={s.artLabel}>CONNECTING<br/>POSSIBILITIES.</span><span className={s.artCoordinate}>IDEA → PRODUCT</span></div></div></section>
  <div className={s.heroBar}><span>하나의 아이디어, 연결되는 가능성.</span><span>제품에 필요한 과정을 함께합니다. <b aria-hidden="true">↓</b></span></div>
  {visibleProjects.length > 0 && <section className={s.section}><div className={s.sectionHeading}><div><p className={s.eyebrow}>SELECTED PROJECTS</p><h2>경험이 담긴 프로젝트</h2></div><Link href="/portfolio" className={s.textLink}>전체 사례 보기 ↗</Link></div><Portfolio/></section>}
  <section className={s.section}><div className={s.sectionHeading}><div><p className={s.eyebrow}>WHAT WE DO</p><h2>아이디어를 현실로 만드는<br/>세 가지 연결.</h2></div><p>필요한 단계부터, 필요한 만큼.<br/>제품에 맞는 실행 방법을 함께 찾습니다.</p></div><Services/><p className={s.note}>사업 소개는 검토용 초안입니다. 직접 수행·협력사 연계와 세부 지원 범위는 개별 상담 후 확인합니다.</p></section>
  <section className={s.processSection}><div className={s.container}><div className={s.sectionHeading}><div><p className={s.eyebrow}>HOW WE WORK</p><h2>함께 이해하고,<br/>끝까지 연결하는 방식.</h2></div><Link href="/about" className={s.textLink}>JNB 알아보기 ↗</Link></div><Process/></div></section><ContactCTA/>
  </>; }
